export const FETCH_LIST_REPOS = 'FETCH_LIST_REPOS';
export const CHANGE_REPO_MESSAGES = 'CHANGE_REPO_MESSAGES';
export const CHANGE_ISLOADING = 'CHANGE_ISLOADING';

export const FETCH_USER = 'FETCH_USER';
export const CHANGE_USER_MESSAGES = 'CHANGE_USER_MESSAGES';

export const FETCH_STARGAZERS = 'FETCH_STARGAZERS';
export const CHANGE_STARGAZER_MESSAGES = 'CHANGE_STARGAZER_MESSAGES';
export const CHANGE_STARGAZER_ISLOADING = 'CHANGE_STARGAZER_ISLOADING';
