export const FETCH_LIST_REPOS = 'FETCH_LIST_REPOS';
export const CHANGE_USER_MESSAGES = 'CHANGE_USER_MESSAGES';
export const CHANGE_REPO_MESSAGES = 'CHANGE_REPO_MESSAGES';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_STARGAZERS = 'FETCH_STARGAZERS';
